import MobileMenu from '@/components/common/MobileMenu/MobileMenu'
import Navbar from '@/components/common/Navbar/Navbar'
import PrimaryToaster from '@/components/common/PrimaryToaster/PrimaryToaster'
import { Providers } from "@/redux/provider"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'remixicon/fonts/remixicon.css'
import './globals.css'
import { NextAuthProvider } from "./providers"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className} >
        <NextAuthProvider>
          <Providers>
            <Navbar />
            <MobileMenu />
            <PrimaryToaster />
            {children}
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  )
}
